@startuml
skinparam rectangle {
  BackgroundColor #FFFFFF
  BorderColor #000000
  FontSize 14
}
skinparam frame {
  BackgroundColor #E8F4F8
  BorderColor #2980B9
  FontSize 14
}
skinparam folder {
  BackgroundColor #FFF9E6
  BorderColor #F39C12
  FontSize 14
}
skinparam component {
  BackgroundColor #E8F8F5
  BorderColor #27AE60
  FontSize 19
}
skinparam interface {
  BackgroundColor transparent
  BorderColor transparent
}
component "<<AtomicRosNodeClassifier>>\nAgeSubscriber" as node {
  portin "callback_on_age" as s1
}
frame "s1" as topic_in_age {
  rectangle "**skeleton::msg::Age**" as t_in_age
}
topic_in_age -[#blue,bold]-> s1
@enduml