@startuml
skinparam rectangle {
  BackgroundColor #FFFFFF
  BorderColor #000000
  FontSize 14
}

skinparam frame {
  BackgroundColor #E8F4F8
  BorderColor #2980B9
  FontSize 14
}

skinparam folder {
  BackgroundColor #FFF9E6
  BorderColor #F39C12
  FontSize 14
}

skinparam component {
  BackgroundColor #E8F8F5
  BorderColor #27AE60
  FontSize 19
}

skinparam interface {
  BackgroundColor transparent
  BorderColor transparent
}

component "<<AtomicRosNodeClassifier>>\nCircleGenerator" as node {
  portin " " as s1
  portout " " as p1
}

frame "s1" as topic_in_counting {
  rectangle "**skeleton::msg::Num**" as t_in_counting
}

frame "p1" as topic_out_square {
  rectangle "**skeleton::msg::Square**" as t_out_square
}

folder "rs1" as service_odd_or_even {
  rectangle "**skeleton::srv::OddOrEven**" as srv_odd_or_even
}

topic_in_counting ---> s1 : callback_counting_logger

p1 ---> topic_out_square
node --( service_odd_or_even
@enduml