@startuml
!theme plain
title System Architecture Toy example

skinparam packageStyle rectangle
skinparam noteFontSize 8
skinparam defaultTextAlignment center

left to right direction

component "to_circle_part" as circle_part <<CamposedRosNodeClassifier>> {
    portin " s1 / skeleton::msg::Circle " as portoutside1
    portin " s2 / skeleton::msg::Circle " as portoutside2
    portout "p1 / skeleton::msg::Circle" as portoutside3
    portout "p2 / skeleton::msg::Circle" as portoutside4

    package "left" as left <<namespace>> #line.dashed;line:grey {
        component ":circle_convertor" as left_circle_converter <<RosNodePart>> {
            portin "s1" as port1
            portout "p1" as port2
}
}
    package "right" as right <<namespace>> #line.dashed;line:grey {
        component ":circle_convertor" as right_circle_converter <<RosNodePart>> {
            portin "s1" as port3
            portout "p1" as port4
}   
}
portoutside1 --[#Blue,bold]--> port1
portoutside2 --[#Blue,bold]--> port3  
port2 --[#Green,bold]--> portoutside3
port4 --[#Green,bold]--> portoutside4

@enduml
